[build]
  command = "npm run build"
  publish = "dist"
  environment = { }

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_VERSION = "9.0.0"
  # Disable secrets scanning for client-side environment variables
  SECRETS_SCAN_OMIT_KEYS = "VITE_EMAILJS_PUBLIC_KEY,VITE_EMAILJS_SERVICE_ID,VITE_EMAILJS_TEMPLATE_ID"
  SECRETS_SCAN_OMIT_PATHS = "dist/**/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
